# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gRPC_store_inventory_pb2 as gRPC__store__inventory__pb2


class ProductInventoryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/addProduct',
        request_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.ProductID.FromString,
        )
    self.addOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/addOrder',
        request_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.OrderID.FromString,
        )
    self.getProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/getProduct',
        request_serializer=gRPC__store__inventory__pb2.ProductID.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.getOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/getOrder',
        request_serializer=gRPC__store__inventory__pb2.OrderID.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.updateProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/updateProduct',
        request_serializer=gRPC__store__inventory__pb2.UpdateProductInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.updateOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/updateOrder',
        request_serializer=gRPC__store__inventory__pb2.UpdateOrderInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.addProductsToOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/addProductsToOrder',
        request_serializer=gRPC__store__inventory__pb2.AddToOrder.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.removeProductsFromOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/removeProductsFromOrder',
        request_serializer=gRPC__store__inventory__pb2.RemoveFromOrder.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.listProducts = channel.unary_stream(
        '/ecommerce.ProductInventory/listProducts',
        request_serializer=gRPC__store__inventory__pb2.ListProductsInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.listOrders = channel.unary_stream(
        '/ecommerce.ProductInventory/listOrders',
        request_serializer=gRPC__store__inventory__pb2.OrderStatus.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )


class ProductInventoryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addProductsToOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeProductsFromOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductInventoryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addProduct': grpc.unary_unary_rpc_method_handler(
          servicer.addProduct,
          request_deserializer=gRPC__store__inventory__pb2.Product.FromString,
          response_serializer=gRPC__store__inventory__pb2.ProductID.SerializeToString,
      ),
      'addOrder': grpc.unary_unary_rpc_method_handler(
          servicer.addOrder,
          request_deserializer=gRPC__store__inventory__pb2.Order.FromString,
          response_serializer=gRPC__store__inventory__pb2.OrderID.SerializeToString,
      ),
      'getProduct': grpc.unary_unary_rpc_method_handler(
          servicer.getProduct,
          request_deserializer=gRPC__store__inventory__pb2.ProductID.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'getOrder': grpc.unary_unary_rpc_method_handler(
          servicer.getOrder,
          request_deserializer=gRPC__store__inventory__pb2.OrderID.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'updateProduct': grpc.unary_unary_rpc_method_handler(
          servicer.updateProduct,
          request_deserializer=gRPC__store__inventory__pb2.UpdateProductInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'updateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrder,
          request_deserializer=gRPC__store__inventory__pb2.UpdateOrderInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'addProductsToOrder': grpc.unary_unary_rpc_method_handler(
          servicer.addProductsToOrder,
          request_deserializer=gRPC__store__inventory__pb2.AddToOrder.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'removeProductsFromOrder': grpc.unary_unary_rpc_method_handler(
          servicer.removeProductsFromOrder,
          request_deserializer=gRPC__store__inventory__pb2.RemoveFromOrder.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'listProducts': grpc.unary_stream_rpc_method_handler(
          servicer.listProducts,
          request_deserializer=gRPC__store__inventory__pb2.ListProductsInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'listOrders': grpc.unary_stream_rpc_method_handler(
          servicer.listOrders,
          request_deserializer=gRPC__store__inventory__pb2.OrderStatus.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecommerce.ProductInventory', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
