# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gRPC_store_inventory_pb2 as gRPC__store__inventory__pb2


class ProductInventoryStub(object):
  """All functions specific to the gRPC server 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.determineSuccessfulConnection = channel.unary_unary(
        '/ecommerce.ProductInventory/determineSuccessfulConnection',
        request_serializer=gRPC__store__inventory__pb2.Empty.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Empty.FromString,
        )
    self.addProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/addProduct',
        request_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.ProductID.FromString,
        )
    self.addOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/addOrder',
        request_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.OrderID.FromString,
        )
    self.getProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/getProduct',
        request_serializer=gRPC__store__inventory__pb2.ProductID.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.getOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/getOrder',
        request_serializer=gRPC__store__inventory__pb2.OrderID.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.updateProduct = channel.unary_unary(
        '/ecommerce.ProductInventory/updateProduct',
        request_serializer=gRPC__store__inventory__pb2.UpdateProductInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.updateOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/updateOrder',
        request_serializer=gRPC__store__inventory__pb2.UpdateOrderInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.addProductsToOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/addProductsToOrder',
        request_serializer=gRPC__store__inventory__pb2.AddToOrder.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.removeProductsFromOrder = channel.unary_unary(
        '/ecommerce.ProductInventory/removeProductsFromOrder',
        request_serializer=gRPC__store__inventory__pb2.RemoveFromOrder.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )
    self.listProducts = channel.unary_stream(
        '/ecommerce.ProductInventory/listProducts',
        request_serializer=gRPC__store__inventory__pb2.ListProductsInfo.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Product.FromString,
        )
    self.listOrders = channel.unary_stream(
        '/ecommerce.ProductInventory/listOrders',
        request_serializer=gRPC__store__inventory__pb2.OrderStatus.SerializeToString,
        response_deserializer=gRPC__store__inventory__pb2.Order.FromString,
        )


class ProductInventoryServicer(object):
  """All functions specific to the gRPC server 
  """

  def determineSuccessfulConnection(self, request, context):
    """
    Determines a successful Connection between client and server
    Parameter: Empty
    Returns: Empty
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addProduct(self, request, context):
    """
    Add a product to the database
    Parameter: Product
    Returns: ProductID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addOrder(self, request, context):
    """
    Add an order to the database
    Parameter: Order
    Returns: OrderID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProduct(self, request, context):
    """
    Get a product from the database by specifying either the product's id value or the product's name
    Parameter: ProductID
    Returns: Product
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrder(self, request, context):
    """
    Get an order from the database by specifying the order's id value
    Parameter: OrderID
    Returns: Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateProduct(self, request, context):
    """
    Update a product currently in the database, denoting it by either its id value or its name
    Parameter: UpdateProductInfo
    Returns: Product
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrder(self, request, context):
    """
    Update an order currently in the database, denoting it by its id value
    Parameter: UpdateOrderInfo
    Returns: Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addProductsToOrder(self, request, context):
    """
    Add products currently in the database to an order or add to the quantity of a product already in an order
    This will update the products stock automatically 
    Parameter: AddToOrder
    Returns: Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeProductsFromOrder(self, request, context):
    """
    Remove products from a order or remove quantities of products already in an order.
    This will update the products stock automatically
    Parameter: RemoveFromOrder
    Returns: Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listProducts(self, request, context):
    """
    List all products currently in the database.
    The list of products can be narrowed down by specifying if product are in stock and/or the manufacturer
    Parameter: ListProductsInfo
    Returns: Stream of Product
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def listOrders(self, request, context):
    """
    List all orders currently in the database.
    The list of orders can be narrowed down by shipped status and/or paid status of the orders
    Parameter: OrderStatus
    Returns: Stream of Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductInventoryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'determineSuccessfulConnection': grpc.unary_unary_rpc_method_handler(
          servicer.determineSuccessfulConnection,
          request_deserializer=gRPC__store__inventory__pb2.Empty.FromString,
          response_serializer=gRPC__store__inventory__pb2.Empty.SerializeToString,
      ),
      'addProduct': grpc.unary_unary_rpc_method_handler(
          servicer.addProduct,
          request_deserializer=gRPC__store__inventory__pb2.Product.FromString,
          response_serializer=gRPC__store__inventory__pb2.ProductID.SerializeToString,
      ),
      'addOrder': grpc.unary_unary_rpc_method_handler(
          servicer.addOrder,
          request_deserializer=gRPC__store__inventory__pb2.Order.FromString,
          response_serializer=gRPC__store__inventory__pb2.OrderID.SerializeToString,
      ),
      'getProduct': grpc.unary_unary_rpc_method_handler(
          servicer.getProduct,
          request_deserializer=gRPC__store__inventory__pb2.ProductID.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'getOrder': grpc.unary_unary_rpc_method_handler(
          servicer.getOrder,
          request_deserializer=gRPC__store__inventory__pb2.OrderID.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'updateProduct': grpc.unary_unary_rpc_method_handler(
          servicer.updateProduct,
          request_deserializer=gRPC__store__inventory__pb2.UpdateProductInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'updateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrder,
          request_deserializer=gRPC__store__inventory__pb2.UpdateOrderInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'addProductsToOrder': grpc.unary_unary_rpc_method_handler(
          servicer.addProductsToOrder,
          request_deserializer=gRPC__store__inventory__pb2.AddToOrder.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'removeProductsFromOrder': grpc.unary_unary_rpc_method_handler(
          servicer.removeProductsFromOrder,
          request_deserializer=gRPC__store__inventory__pb2.RemoveFromOrder.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
      'listProducts': grpc.unary_stream_rpc_method_handler(
          servicer.listProducts,
          request_deserializer=gRPC__store__inventory__pb2.ListProductsInfo.FromString,
          response_serializer=gRPC__store__inventory__pb2.Product.SerializeToString,
      ),
      'listOrders': grpc.unary_stream_rpc_method_handler(
          servicer.listOrders,
          request_deserializer=gRPC__store__inventory__pb2.OrderStatus.FromString,
          response_serializer=gRPC__store__inventory__pb2.Order.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecommerce.ProductInventory', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
